### PR TITLE
Fix error case in CNavMesh.BuildPath + add natives

### PR DESCRIPTION
**Pull request by KitRifty**
Passing `NULL_AREA` then a valid goal position into BuildPath will always return false due to `CNavArea::Contains` not implemented properly. https://github.com/TF2-DMB/CBaseNPC/blob/c5c2c4a255eccfa4867a3ba770b5ef160d51fa51/extension/sourcesdk/nav_area.h#L244

This fixes this case, along with exposing the following natives:
- `CNavArea.IsOverlappingX`
- `CNavArea.IsOverlappingY`
- `CNavArea.GetExtent`
- `CNavArea.ContainsPoint`

This also adds some more stocks that area useful for working with directions:
- `DirectionLeft`
- `DirectionRight`
- `DirectionToAngle`
- `AngleToDirection`

### CODE REVIEW

**Review by Kenzzer — DISMISSED** [review]

**Comment by Kenzzer** [comment]
Hijacked this PR to add my navmesh update as well.

**Comment by Kenzzer** [comment]
I got a report from @Mikusch who's currently trying a manual build of this PR on his servers, if the extension is late loaded the extension's `TheNavMesh` is consequently null, due to `CNavMesh::AddNavArea` function being already called. This is a direct consequence of me changing to retrieval method of `TheNavMesh` however this also unearth another bug which plagues previous versions of CBaseNPC, as `CNavMesh::AddNavArea` detour is also used to fill `TheNavAreas`.

Should we address the late load issue, or should we let it slide and make it mandatory not to late load the extension ? This could also have consequences for our local testing of the extension (having to change map, between reloads).

**Review by KitRifty — COMMENTED** [review]
Everything looks solid to me for the most part, but discussion is needed on a particular edge case. Also, gamedata and include files need to be updated too.

**Comment by KitRifty** [comment]
> however this also unearth another bug which plagues previous versions of CBaseNPC, as CNavMesh::AddNavArea detour is also used to fill TheNavAreas.

Can you elaborate on this bug?

> Should we address the late load issue, or should we let it slide and make it mandatory not to late load the extension ?

The former, which my previous review addresses. The old retrieval method should work fine in late load circumstances, though personally I prefer to auto-load the extension.

**Comment by Kenzzer** [comment]
> Can you elaborate on this bug?

Well, `CNavMesh::AddArea` detour, used to be the entry point to fill `TheNavAreas` vector. However, if the extension was late loaded, that vector would be empty (this plagues all versions of CBaseNPC pior to this PR). This has now been resolved with the latest commits.

**Comment by KitRifty** [comment]
No further comments, everything looks good to me. 👍

**Pull request merged**
